baseurl = "https://tombrereton.github.io/PortfolioWebsite/"

title = "Tom Brereton"
author = "Tom Brereton"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"
buildDrafts = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Tom Brereton"
  disqusShortname = "thomasbrereton"

[[menu.main]]
    name = "Projects"
    url  = "/projects/"
[[menu.main]]
    name = "Resume"
    url  = "/resume/"
[[menu.main]]
    name = "Blog"
    url  = "/post/"

